version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    # Look for a solution file or a project file in the root directory
    directory: "/"
    schedule:
      # Check for updates daily
      interval: "daily"
    groups:
      # Group all NuGet packages together.
      # This is a workaround for a Dependabot issue where it incorrectly adds
      # 'Version' attributes to .csproj files when using Central Package Management.
      # Grouping all updates can help Dependabot process the updates correctly.
      nuget-packages:
        patterns:
          - "*"