using System.Reflection;
using VmMachineHwVersionUpdater.Avalonia.Views;

namespace VmMachineHwVersionUpdater.Avalonia.Tests.Views;

public class AddEditAnnotationDialogTests : AvaloniaTestBase<App>
{
    [Fact]
    public void Constructor_HasNullGuards()
    {
        // Constructor has no parameters, so no null guards to test
        typeof(AddEditAnnotationDialog).GetConstructors().Should().NotBeEmpty();
    }

    [Fact]
    public void Constructor_ReturnsInterfaceName()
    {
        // Test that the type is assignable to Window without actually instantiating
        typeof(AddEditAnnotationDialog).Should().BeAssignableTo<Window>();
    }

    [Fact]
    public void Methods_HaveNullGuards()
    {
        // Only test methods declared in our class, not inherited Avalonia methods
        var methods = typeof(AddEditAnnotationDialog)
                      .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                      .Where(m => !m.IsAbstract && !m.IsSpecialName);

        // Exclude InitializeComponent which is generated by Avalonia XAML compiler
        var customMethods = methods.Where(m => m.Name != "InitializeComponent").ToArray();
        customMethods.Should()
                     .BeEmpty("AddEditAnnotationDialog should not have custom public methods besides InitializeComponent");
    }
}